#!/bin/bash

# init vars
OPTIND=1
nap=10m
notif=0
verbose=0
save_dir="$HOME/screenstalk"
[[ ! -d $save_dir ]] && mkdir $save_dir

# init functions
print_help_and_exit () {
  echo "Usage: screenstalk [OPTIONS]"
  echo "Options:"
  echo " -t       interval   (default: 10m)"
  echo " -n       send a notification before every screenshot"
  echo " -v       be verbose"
  echo " -h       print help (this message)"
  exit $1
}

loop_stop () {
  if [[ $verbose == 1 ]]; then
    echo
    echo "Interrupt signal received"
  fi
  exit 0
}

# getopts
while getopts "t:nvh?" opt; do
  case "$opt" in
    t) # time / interval
      nap=$OPTARG
      ;;
    n)
      notif=1
      ;;
    v)
      verbose=1
      ;;
    h|?)
      print_help_and_exit 0
      ;;
  esac
done

trap loop_stop INT

# the loop
i=0
while true; do
  sleep $nap
  if [[ ! $? == 0 ]]; then
    echo "Invalid interval"
    exit 1
  fi

  screen="$save_dir/$(date +%Y%m%d_%H%M%S)_$i.jpg"
  [[ $verbose == 1 ]] && echo fullpath: $screen
  [[ $notif == 1 ]] && notify-send "ScreenStalk" "Taking screenshot..."
  import -window root $screen

  i=$(( $i + 1 ))
done
